README.md

This PR introduces new `README.md` file. My goal was to keep it unified with other community repos.
I've copied `props` documentation from https://github.com/facebook/react-native-website

New README.md file

---

js/RNCSliderNativeComponent.js
js/Slider.js

removed haste imports from Slider component

Remove haste imports from Slider 

---

react-native-slider.podspec

Add pod file

---

package.json
typings/index.d.ts

Summary:
---------
Inspired from: https://github.com/react-native-community/react-native-viewpager/pull/10
imported from `@types/react-native`
Test Plan:
----------
N/A

chore: added typings

---

package.json

Summary:
---------
I added needed script in package.json
Test Plan:
----------
Green CI

Add test:jest script

---

.prettierrc
package.json

Summary:
---------
Remove unused `.prettierrc` file
Test Plan:
----------
Green CI

remove unused .prettierrc

---

README.md

Summary:
---------
Fixes https://github.com/react-native-community/react-native-slider/issues/6 https://github.com/react-native-community/react-native-slider/issues/29
Added example screenshots, removed the unused prop from an example in the README.
Test Plan:
----------
Review if images in `README.md` file are displayed properly.

Add screenshots, remove unused prop from README

---

.circleci/config.yml
package.json

Summary:
---------
Migrated to React Native CircleCI Orb to match rest of the community repos.
Test Plan:
----------
CI should be green.

chore: migrate to circleci orb

---

android/build.gradle
android/gradle.properties
android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
example/android/app/build.gradle
example/android/build.gradle

Reverts react-native-community/react-native-slider#47

Revert "Use AndroidX support lib"

---

react-native-slider.podspec

update podspec for fix error during "pod install"
Summary:
---------
Test Plan:
----------

fix "Could not find remote branch" error

---

package.json
yarn.lock

Summary:
---------
Resolved GitHub security alerts.
Test Plan:
----------
N/A

Resolve security vulnerabilities

---

README.md
example/ios/Podfile.lock
package.json
yarn.lock

Summary:
---------
Stable 2.0.0 release. Updated readme, bumped RN and RN Cli, resolved lodash vulnerability, and added missing debug keystore.
Test Plan:
----------
N/A

2.0.0 stable

---

android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
example/SliderExample.js

Summary:
---------
Resolve https://github.com/react-native-community/react-native-slider/issues/9
Test Plan:
----------
Add code to example:
https://github.com/ptrocki/react-native-slider/commit/869188d329fa4a168b2959bc01421f86ceac7814
And click the button few times.

Fix circular dependencies animatorset

---

example/ios/Podfile.lock

Summary:
---------
Update podfile
Test Plan:
----------
Install pods

chore: update podfile

---

src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
yarn.lock

Summary:
---------
fixes #100 
Test Plan:
----------
run `./assemble build` in example project

fix: solve build issue with wrong value in measure spec

---

src/typings/index.d.ts

Summary:
---------
Just added slider prop to index.d.ts :)
Resolves #129

Add inverted prop to index.d.ts

---

src/ios/RNCSlider.m

Summary:
---------
Fixes #134 #131
Test Plan:
----------
Touch to seek and confirm that there's no flicker.

Fix touch to seek flicker on iOS

---

example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj
example/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme

Summary:
---------
Added a script to start packager automatically in an example, removed missing leftovers from RN <60 
Test Plan:
----------
Test if example works.

Start packager automatically in example, fix xcode project for RN 61

---

src/package.json
yarn.lock

chore: update to 2.0.7

---

README.md

Summary:
---------
Updates contribution section of README to highlight the fact that yarn needs to be used to correctly download dependencies.
Test Plan:
----------
No new tests added.
Related issues:
Closes #166

Updates contributing section in README

---

.eslintignore
.eslintrc.json
.gitignore
example/App.js
example/README.md
example/SliderExample.js
example/app.json
example/babel.config.js
example/index.web.js
example/ios/Podfile.lock
example/package.json
package.json
src/js/RNCSliderNativeComponent.web.js
yarn.lock

Summary:
---------
Fixes #183 and #163 transitively.
Also fixed example on Android and added web support to example project to be able to test it easily.
Test Plan:
----------
CI passes, examples run and work on all platforms

Fix rounding bug

---

src/package.json

Summary:
---------
Release 3.0.1

chore: update to 3.0.1

---

src/package.json

Summary:
---------
Release 3.0.2

chore: update to 3.0.2

---

src/typings/index.d.ts

Summary:
---------
Add `tapToSeek` to types.
Test Plan:
----------
No since only changing types.

Add tapToSeek to types

---

.npmignore

Summary:
---------
- Exclude test files: https://npmfs.com/package/@react-native-community/slider/3.0.3/js/__tests__/
Test Plan:
----------
```
npm pack --dry-run
```

[other] Reduce npm package size

---

src/package.json

This pull request upgrades the version of the library in *package.json* to *v.4.1.2*.
This release will contain all the minor version updates done by the `dependabot`.

Release 4.1.2: Bump version in package.json

---

src/package.json

Due to the released package the version in *src/package.json* has been updated to *4.1.4*.

Release 4.1.4: Bump version in package.json

---

src/android/build.gradle

Adding mavenCentral() as jcenter() is shutting done

Adding mavenCentral() as jcenter() is shutting

---

src/package.json
yarn.lock

This pull request updates the version of the library to *v4.1.11*.

Release: version update to v4.1.11

---

src/package.json
yarn.lock

This pull request updates the version of the library to 4.2.1.

Release - version update 4.2.1

---

src/package.json
yarn.lock

This pull request releases the v4.2.2 of the package.

Release: v4.2.2

---

src/package.json
yarn.lock

This pull request updates the *yarn.lock* file by reinstalling the node_modules with clean lockfile.
All dependencies were refreshed according to the recent releases.
This pull request probably should fix at least some of the security/dependabot issues.

Update yarn.lock file

---

src/package.json
yarn.lock

This pull request releases v4.2.3
This release contains the hotfix for the reported defect, where default value was ignored on Android.

Release: v4.2.3

---

example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj
src/package.json
yarn.lock

This pull request releases the Slider v4.2.4.

Release: v4.2.4

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates the version of Slider to 4.3.0

Release: v4.3.0

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates the package version and repository to v4.3.1

Release: version 4.3.1

---

README.md

Summary:
---------
Added useful information about the new architecture setup for easier testing.

Add info about new architecture to README

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates the package version and repository to v4.3.2

Release: version 4.3.2

---

example/ios/Podfile.lock
example/ios/example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
example/package-lock.json
package/package-lock.json
package/package.json

This pull request releases the version 4.3.3 of the Slider.

Update package to v4.3.3

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request releases the Slider in version 4.4.0.

Release: v4.4.0

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates the Slider package to the v4.4.1

Release: version 4.4.1

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates Slider package to v4.4.2

Release: version 4.4.2

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates Slider package to v4.4.4

Release: version 4.4.4

---

README.md

I'm working on fully describing the new features of `StepMarker` and steps indicator.
This PR introduces the changes.
Hoping for some community devs/folks to provide it with some questions/comments/remarks 🙏

Add 'StepMarker' and 'renderStepsIndicator' to the README

---

README.md
example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request updates the Slider to v4.5.1
**Note:** As I'm not yet releasing the custom step marker in it's tip-top shape, I marked those two new props as experimental. There's still some work to be done with those, but it could be valuable to let community play with it a little and provide the feedback.

Release: version 4.5.1

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request releases Slider to v4.5.2

Release: version 4.5.2

---

package/android/gradle.properties

Summary:
---------
fixes #580 
Raise library's version from 29 to 30
Test Plan:
----------
Checked the example app on emulators with 
Android 29
Android 30
Android 35
And it builds and works correctly for those targets

fix: raise supported android sdk

---

README.md

This pull request updates the maintainers section,
and invites @draggie to support the maintenance of Slider!

Update the Maintainers section in README

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request releases the Slider with version 4.5.3

Release: version 4.5.3

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request releases Slider in v4.5.5

Release: version update 4.5.5

---

example/ios/Podfile.lock
example/package-lock.json
package/package-lock.json
package/package.json

This pull request releases Slider with version 4.5.6.

Release: v4.5.6
