callstack/react-native-slider

- LICENSE
Added MIT license to project. 
License is the same as https://raw.githubusercontent.com/react-native-community/react-native-cli/master/LICENSE with updated year
> Chore: Add MIT license

- README.md
Summary:
---------
Gradle 5 introduces new rules for which characters are allowed in project names:
> You can no longer use any of the following characters in domain object names, such as project and task names: <space> / \ : < > " ? * | . You should also not use . as a leading or trailing character.
This PR removes the `/` that is now not allowed.
This means that new users who setup the library now will not be affected when upgrading to Gradle 5. Existing users will get an error message like this and will need to make the change manually:
```
* What went wrong:
A problem occurred configuring project ':@react-native-community/slider'.
> The project name '@react-native-community/slider' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the …
```
> docs(README): Allow the Android manual linking instructions to work with Gradle 5+

- package.json
Summary:
---------
Currently, this is the error that shows up when trying to use the Slider in a project: 
```bash
error: bundling failed: Error: While trying to resolve module `@react-native-community/slider` from file `/Users/karanthakkar/Work/Repos/Personal/react-native-gesture-handler/Example/combo/index.js`, the package `/Users/karanthakkar/Work/Repos/Personal/react-native-gesture-handler/Example/node_modules/@react-native-community/slider/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/karanthakkar/Work/Repos/Personal/react-native-gesture-handler/Example/node_modules/@react-native-community/slider/index`. Indeed, none of these files exist:
* …
```
> fix: add "main" field in package.json to avoid metro error

- package.json
Summary:
---------
With the latest update to React-Native 0.59, the Slider component has been deprecated from react-native core and has been moved to this community package.
When adding the new `@react-native-community/slider` to a project that has a podfile– the `pod install` would not complete due to validation issues with the podspec file. https://github.com/react-native-community/react-native-slider/blob/master/react-native-slider.podspec
This should resolve the issue from #21 – I'm willing to bet as more people begin to upgrade to RN 0.59 today they will run across this issue.
Test Plan:
----------
This adds the missing fields to the package.json file so that the pod install can successfully run.
Cocoapods is still a bit of a pain-point in react-native development and will be …
> Update package.json to satisfy podspec checks

- README.md
Summary:
---------
Small typo in the README for the manual linking step on Android. Caught me out. netinfo -> slider
Test Plan:
----------
N/A
> chore: Fix typo in README for manual linking

- typings/index.d.ts
Summary:
---------
Types are imported from react-native package, and Slider component don't have default export there, but in this community package usage is with it.
So default keyword missing from types, causing TS compile error:
`JSX element type 'Slider' does not have any construct or call signatures.`
PR fix this.
Test Plan:
----------
N/A
> fix: Add missing default keyword to types

- android/build.gradle
- android/gradle.properties
- android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- example/android/app/build.gradle
- example/android/build.gradle
Summary:
---------
Use AndroidX in place of legacy Android support libraries. This is required for any Android projects that use AndroidX for support libraries.
See: `https://developer.android.com/jetpack/androidx/migrate`
Specifically react-native-gesture-handler currently has a 4 PRs to migrate to AndroidX being blocked by this down stream dependency for our tests that require react-native-slider.
> Use AndroidX support lib

- typings/index.d.ts
Summary:
---------
I use TypeScript to develop my react-native app. When I use `onSlidingStart` prop, I received a error message from transpiler, because of `onSlidingStart` prop definition is not contains in `typings/index.d.ts`.
> Add onSlidingStart prop on SliderProps interface in index.d.ts

- README.md
- android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
- example/SliderExample.js
- js/Slider.js
Summary:
---------
I've added a "inverted" variable to slider for Android. It allows to invert the slider direction.
It fixes issue #39.
Also the issue #69 has been fixed.
Test Plan:
----------
Issue #39
You can set the "inverted" variable of a Slider component and it'll change its direction.
`<SliderExample inverted />`
----------
Issue #69
You can check the fixed issue #69 with follow code:
(I've checked it in Android-s with API: 19, 24, 25, 28)
`<Slider style={{ width: 100, transform: [{ rotate: '-90deg' }] }} />`
> Inverted slider android

- android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
- example/SliderExample.js
- js/Slider.js
- js/__tests__/__snapshots__/Slider.test.js.snap
Summary:
---------
This implements the `thumbImage` prop also for Android.
Test Plan:
----------
Changes were tested in both iOS and Android emulator, each in debug mode. This branch is also used in a production app, so it also works in release mode.
Regarding the thumbImage size for iOS: https://github.com/react-native-community/react-native-slider/issues/105
> feat: Implement thumbImage for Android

- react-native.config.js
Summary:
---------
Yarn and `npx` differ in how they treat `process.cwd()`, with Yarn changing it to where the `yarn.lock` file is, and with `npx` not touching it (which also makes sense). To account for that, and for future CLI changes in this area, let's use `__dirname` (or path.resolve('.') but dirname is simpler), because this is the actual path we want the `root` to be resolved to.
Test Plan:
----------
Test example app
> fix: use __dirname instead of unstable process.cwd in RN config file

- src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
Fixes https://github.com/react-native-community/react-native-slider/issues/119
In debug mode RNs "Image.resolveAssetSource" method returns http-uri and in release mode that returns android resource name. Previously the case where it returns an android resource name was not handled.
> Fix missing thumbImage on android release mode

- README.md
- example/README.md
- example/package.json
- package.json
- src/package.json
Summary:
---------
Hi, I wanted to play around the package, but I had difficulties to run the example app. 
I decided to add proper scripts in `example` directory and add simple instructions for contributors.
I have written instructions in a similar manner as in `react-native-tab-view` repo.
Test Plan:
----------
1. Read added docs and verify if they are correct and useful.
2. Test if added scripts work.
> docs: add run example scripts and contribution instructions

- example/SliderExample.js
- example/package.json
- src/js/RNCSliderNativeComponent.js
- src/js/Slider.js
Summary:
---------
Fixes https://github.com/react-native-community/react-native-slider/issues/133
That PR is:
* replacing `require()` in favour of `import`
* fixing `start` command in example
* adding default exports
Test Plan:
----------
> Refactor imports exports

- src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
Fixes https://github.com/react-native-community/react-native-slider/issues/123
Reverts react-native-community/react-native-slider#75 as it has introduced https://github.com/react-native-community/react-native-slider/issues/123
> Revert "Fix circular dependencies animatorset"

- README.md
Summary:
---------
`thumbImage` became cross-platform in #106
> Readme: Remove `platform` column for `thumbImage`

- src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
- src/ios/RNCSlider.h
- src/ios/RNCSlider.m
- src/ios/RNCSliderManager.m
- src/js/RNCSliderNativeComponent.js
- src/js/Slider.js
- src/typings/index.d.ts
Summary:
---------
Add accessibility improvements for screen readers to announce custom units.
Currently there are no capabilities for custom screen reader output with this component. This PR would allow consumers to specify a custom unit to be read by the screen reader, instead of just the default `percent` value. It is an optional field, so if nothing is specified it will use the default behavior.
There is one minor caveat:
- On iOS everything is overridden as expected
- On Android, the default values are still announced, along with the additional custom values. This seems to be due to some limitations of accessibility in RN 61, and the `ReactAccessibilityDelegate`
Test Plan:
----------
I tested this by replacing the yarn library with my local copy in my existing application, that I …
> Add accessibility improvements for screen readers

- src/js/RNCSliderNativeComponent.web.js
Signed-off-by: François BILLIOUD <f.billioud@gmail.com>
Summary:
---------
Fix for #176
Can be tested with @sharcoux/slider version 2.0.16
I'm working on a sandbox.
> Prevent slider from overflowing out of the container in Web #176

- README.md
Summary:
---------
The link of color should point to ReactNative's document.
Currently, the link points to a 404 page.
Test Plan:
----------
No test.
> docs: fix links of color in README

- example/SliderExample.js
- src/ios/RNCSlider.m
Summary:
---------
First thanks for this package everyone, I appreciate it
I want the slider on iOS to handle tap events by sliding to the tap.
It's been tried before: #117 implemented tap-handling for iOS, and it worked, mostly
But: #131 #134 were documented regressions from #117
So #136 reverted the change from #117 as the understandable quick fix
I investigated the original PR because I really wanted it to work, and discovered that it was just a mis-match between the values the tap handler propagated compared with what the value consumer wanted
Specifically:
- value emitted was pure 0 through 1 inclusive percentage where the slider was tapped
- value consumed was expected to be the range value from minimum to maximum
So:
- I reverted the revert from #136 / @michalchudziak 
- That …
> Re add ios tap handler

- README.md
- src/js/RNCSliderNativeComponent.web.js
- src/typings/index.d.ts
Allow to control of value by ref (only for web version so far).
`ref.current.updateValue(value: number)`
https://github.com/react-native-community/react-native-slider/issues/205
> share ref with update method

- src/js/RNCSliderNativeComponent.web.js
Summary:
---------
A regression was introduced in PR #186 
https://github.com/react-native-community/react-native-slider/pull/186/files#diff-5847c2317e1d89fb73fd4d87ff989ce6R253
where 
`onValueChange(withinBounds);`
became
`onValueChange(value);`
Therefore value is not correctly changed, preventing to reach min and max values
Test Plan:
----------
Test with a slider from 0 to 100 (%) with step of 1.
Trying to slide to min and max.
**Before**
Cannot reach 0 and 100
**After**
Able to reach 0 and 100
> Fix regression from #186

- src/typings/index.d.ts
Set typing for `ref` prop to be optional
> set ref prop as optional

- src/js/RNCSliderNativeComponent.web.js
Summary:
---------
I had an issue on web at work. We ended up not using a different approach but I spotted the difference between web and mobile behaviour and how to fix it before we did.
Test Plan:
----------
I used the updated version in an ejected Expo app as it was the easiest way to get react-native-web support for free. Test by clicking on the slider instead of dragging.
> Update value on web onTouchEnd so clicking also updates the slider position

- README.md
- example/SliderExample.js
- src/ios/RNCSlider.h
- src/ios/RNCSlider.m
- src/ios/RNCSliderManager.m
- src/js/Slider.js
- src/js/__tests__/__snapshots__/Slider.test.js.snap
Summary:
---------
This feature fork started out adding a tapToSeek prop to allow us to disable that functionality on iOS. The main motivation for this was to avoid inadvertent scrolling on touch down on iOS. Found what may be causing the inadvertent scrolling and fixed that (simulator only unfortunately - I don't a physical device). Also added the originally requested tapToSeek prop to make this functionality opt in on iOS.
Believe this fixes #156, fixes #211, fixes #212 and maybe fixes #147 as well.
Test Plan:
----------
Locally run yarn test passes.
CircleCI tests pass.
Visually inspect on iOS simulator and Android emulator. 
Tweaked one of the examples to demonstrate the tapToSeek behaviour.
> Add tapToSeek prop, fix unintentional scrolling, call onValueChanged when tapping

- example/SliderExample.js
Summary:
---------
Seemed a shame to have validate:eslint marred by a warning, so threw the inline style in to StyleSheet.create.
Test Plan:
----------
`npx yarn test` in example directory passes.
Verified example app visually on iOS and Android emulators.
> Refactored inline style to address eslint warning.

- example/ios/Podfile
- example/ios/Podfile.lock
Summary:
---------
Due issues with `npx pod-install` the `jscallinvoker` was replaced by
`callinvoker`. Running `npx pod-install` again, changed the .lock file.
https://stackoverflow.com/a/60881827/5444033
Test Plan:
----------
This script should run without any errrors:
```
#!/bin/sh
git clone git@github.com:react-native-community/react-native-slider.git
cd react-native-slider
yarn
cd src
yarn
cd ..
cd example
npx pod-install
yarn run:ios
```
> Fix running example project for first time

- src/react-native-slider.podspec
Summary:
---------
One of the projects I'm working on stopped working after updating xcode to latest version. I've found that Xcode 12 fails to build if a module depends on React instead of React-Core. 
Reference: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
This requires RN 0.60.2 or newer.
Test Plan:
----------
Unfortunately, I was unable to run example even after fixing `jscallinvoker`issue. However, all of my projects that use this module started working on xcode 12 after patching the podspec to use React-Core.
> fix: xcode 12 compatibility

- src/ios/RNCSliderManager.m
If the slide was quick, the new tap gesture recognizer would be
invoked and cause the slider to return to its original position
(ignoring the slide).
Summary:
---------
This fixes a problem introduced by #233 where the slider sometimes returns to its original position after a slide. To reproduce the problem, do a quick slide (short distance) with a slider that has `tapToSeek=true`.
Test Plan:
----------
Tested interactively on iOS and Android.
> iOS: Fix problem where slider returned to original position.

- src/js/RNCSliderNativeComponent.web.js
Summary:
---------
The function inside `useEffect` shouldn't return a value, it can only return a function or nothing
This solves this warning:
```
Warning: An effect function must not return anything besides a function, which is used for clean-up. You returned: 0
in RTCSliderWebComponent (at Slider.js:279)
```
It also fixes an error that was breaking the slide in my rn-web app:
Test Plan:
----------
Tested on the examples
> fix: useEffect should not return a value

- src/windows/SliderWindows/SliderWindows.vcxproj
Summary:
---------
Currently, manually linking the react-native-slider to a react-native-windows project requires additional modifications to the vcxproj file located in the node_modules while other projects such as [Picker](https://github.com/react-native-picker/react-native-picker) do not.
Note: Code was copied from [Picker](https://github.com/react-native-picker/react-native-picker/blob/master/windows/ReactNativePicker/ReactNativePicker.vcxproj) vsxproj.
Test Plan:
----------
Perform the manual linking steps on Windows described in the README. Should work on a brand new react-native project created through these [steps](https://microsoft.github.io/react-native-windows/docs/getting-started).
> Fix vcxproj path to node_modules

- src/windows/SliderWindows/SliderWindows.vcxproj
Summary:
---------
Fix error produced when module is added to a React Native app and run in Windows emulator.
Error reads: "The target "Deploy" does not exist in the project".
Test Plan:
----------
Create a React Native Windows app.
Add datetimepicker module to app via yarn add.
Run npx react-native run-windows.
If app deploys successfully and loads in the Windows emulator, the code change has succeeded.
> Resolve Missing Deploy Target Issue

- README.md
- example/package.json
- example/windows/SliderTestWindows.sln
- src/package.json
- src/windows/SliderWindows/SliderWindows.vcxproj
- yarn.lock
Summary:
---------
Autolinking has been implemented in React Native for Windows. Updating the module config to use it.
Additionally, I'm fixing the version number of RNW in package.json - currently it results in a 0.62rc being used, even though multiple newer releases have been made. It's necessary to use the later versions, since they contain a build fix for a problem with Folly and Visual Studio.
Test Plan:
----------
Created a new RNW app, added this module `yarn add @react-native-community/slider@4.0.0-rc.2`
Autolinking is applied when running `npx react-native run-windows`
When first building with Visual Studio, run npx react-native autolink-windows, then build.
> Update project config to enable autolinking on Windows.

- src/windows/SliderWindows/SliderView.cpp
- src/windows/SliderWindows/SliderView.h
Summary:
---------
On Windows, if the `step` property is not specified, the app crashes when trying to move the slider - adding a default value in the native code to prevent that (the default in JS doesn't work).
Also, fixing a casting bug where min/max values get trimmed if fractions are provided.
Fixes #256
> Fix crash when step property is missing on Windows.

- README.md
- src/windows/SliderWindows/SliderView.cpp
- src/windows/SliderWindows/SliderView.h
This pull request fixes #256 
Summary:
---------
This PR provides the Slider with the fix for an application crashing when moving the Slider with a default value set for `<Step/>`.
The implementation introduces the similar approach to step's calculations as is already done for other platforms
(see implementation for [iOS](https://github.com/callstack/react-native-slider/blob/e7dd6eec8796832487afb886719ed622f575e5f6/src/ios/RNCSliderManager.m#L59-L61) and for [Android](https://github.com/callstack/react-native-slider/blob/e7dd6eec8796832487afb886719ed622f575e5f6/src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java#L183-L185)).
The calculations done on Windows implementation returns the default step as 1% of available range: minimum to maximum.
NOTE: The implementation …
> Fix: Slider default step causes crash on Windows OS

- .circleci/config.yml
- example/ios/Podfile.lock
- example/package.json
- src/package.json
- yarn.lock
Summary:
---------
There was a problem with dependencies installation.
Steps to reproduce the **deps not linked in iOS**:
- clone the repo and `cd react-native-slider`;
- run `yarn`
- `cd example; npx pod-install`
- open Xcode `xed -b ios` and go to `/Pods/Development Pods`, click on `react-native-slider` and check the full path in the inspectors. It should be `../src` in order for linking to work properly, and it's `../example/node_modules/react-native-slider`. In other words example app is using installed dependency of `react-native-slider` from its `node_modules`, while it should be using the one from the `../src` in order to show native module changes while development.
Steps to reproduce the **installation problem with detox**:
- Clone the repo and `cd react-native-slider`
- run …
> Fix deps not linked on iOS. Fix installation problem with detox.

- .circleci/config.yml
- example/ios/Podfile.lock
- example/package.json
- src/ios/RNCSlider.h
- src/ios/RNCSlider.m
- src/package.json
- yarn.lock
Summary:
---------
Fixing issue [#271 ](https://github.com/callstack/react-native-slider/issues/271) **only** for iOS.
Behavior after fix:
- `trackImage`
- `trackImage` and `minimumTrackImage` 
- `trackImage` and `maximumTrackImage`
- `trackImage and `minimumTrackImage` and `maximumTrackImage`
Test Plan:
----------
Manually tested with other properties - works as before the changes.
> Fix minimumTrackImage, maximumTrackImage, and trackImage do not work together

- src/ios/RNCSliderManager.m
Summary:
There was an [issue](https://github.com/callstack/react-native-slider/issues/264) caused by rounding problem on iOS native side.
So the basic `round` function was replaced by `ceil` when the slider goes up, and with `floor` when the slider goes down.
The problem:
https://user-images.githubusercontent.com/12425395/115276870-069e4c00-a15d-11eb-805f-8b2f2e6f2208.MP4
Has gone...
https://user-images.githubusercontent.com/12425395/115276646-b58e5800-a15c-11eb-9266-45c3aeedb648.MP4
Test Plan:
Manually check with VoiceOver and confirm that functional has not been changed, only the problem has gone.
> Fixed rounding problem, the cause of issue #264.

- src/ios/RNCSliderManager.m
Summary:
After fixing the issue #264, the new bug pops up and was left unnoticed.
If the slider is continuously scrolled, the slider thumb jumps sporadically.
https://user-images.githubusercontent.com/12425395/116679984-98f7e880-a9c4-11eb-95ab-e80240a20c70.mov
Now the bug is fixed.
Test Plan:
Manually test that the slider works fine while sliding, and with VoiceOver.
> Fix bug, caused by fixing issue #264.

- README.md
- src/README.md
- src/package.json
This pull request updates in general the README.
The improvements and changes are:
* Layout improved
* Badges fixed and updated
* Properties presented in more compressed but readable way
(table instead of separate sections)
* Unified example of usage with combined information about other platforms
* Links updated
* Footer of Callstack used
To check this README document go to [feature/readme-update](https://github.com/callstack/react-native-slider/blob/feature/readme-update/README.md) branch and check the README.
---
**NOTE:** this pull request also adds the README to the *src/* directory which is published in the npm.
This way it will also be displayed on the npm site (currently it is completely empty which looks sad and abandoned).
There's also the version bumped to the latest at the …
> README updated and included in npm package

- src/package.json
- yarn.lock
This pull request fixes #307 
It removes the React, React Native and React Native Windows from `devDependencies` when it comes to *src/package.json* - package dependencies.
The reason that these can be safely removed is that these libraries are also listed in the `peerDependencies` which makes them still being checked when installing.
Both workspaces should not be affected as *src/* should use the packages provided by the consumer, while *example/* should satisfy `peerDependencies` by having them installed in the example app
(moreover: *example* is about to change in upcoming deliveries).
> Fix: Remove redundant React, Rreact Native & React Native Windows from `devDependencies`

- src/package.json
This pull request is a quick followup of #308 
It specifies the `peerDependencies` to use major versions bigger or equal to the specified in *src/package.json*.
> Fix: `peerDependencies` should require bigger or equal versions

- example/android/build.gradle
This pull request fixes the build error of Android Example app:
```
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
> Could not resolve org.webkit:android-jsc:+.
Required by:
project :app
> Failed to list versions for org.webkit:android-jsc.
> Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
> Could not get resource 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
> Could not GET 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
> Read timed out
```
and others.
This pull request is related to [JCenter Serive update](https://developer.android.com/studio/build/jcenter-migration) announcement.
> Use mavenCentral instead of jscenter for Android example app

- src/README.md
The examples animations are now also given to the npm.js package's README.
The way to do that is to point to exact image (.gif) in the blob of master.
The only drawback of that is that it's going to be outdated once the examples change their place in the repository.
---
To test please visit the [README](https://github.com/callstack/react-native-slider/tree/fix/examples-in-package-readme/src#readme) of package in this branch.
> Update the Examples in package's README

- example/android/build.gradle
- src/android/gradle.properties
This pull request updates the `compileSdkVersion` from 28 and 29 to 30, so that the API level 30 can be safely used in further implementation.
This is also related to #323 where such changes are required for the CI to pass.
> Update the `compileSdkVersion` for both lib and example

- example/android/build.gradle
- src/android/gradle.properties
- src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
Summary:
---------
- For Android 11.0 devices, while sliding we are only hearing the percentage of the slider but not `accessibilityIncrements` and `accessibilityUnits`. It is working fine for the other versions below Android 11.
- As part of this PR we are fixing this issue in Android 11 devices.
- I have tested this in various android versions(Android 9, Android 10, Android 11) devices with this fix, it is working perfectly now.
https://drive.google.com/file/d/1mfqT6bfyoVfSETyN89gtEo3golnJKiId/view?usp=sharing
https://drive.google.com/file/d/1ADx0VLZxxtxni-_MozDAyNBLu2cS_HwJ/view?usp=sharing
https://drive.google.com/file/d/1nL1e9410y6pdMmjFUXuImYJWqz8Xqrbl/view?usp=sharing
Test Plan:
----------
- Changes were tested manually in different Android versions of devices.
> ISSUE-319-Accessibility not working perfectly in Android 11 devices 

- src/package.json
This pull request fixes #333 
It removes the *react-native-windows* from `peerDependencies`.
It turns out that if installing this package for an application with react-native, the react-native-windows being required is not always met. And it doesn't have to be met, so requiring this package for every case can lead to conflicts.
**NOTE:** removing this from `peerDependencies` is still safe, because when using this app for Windows development, the react-native-windows has to be installed in the first place, so there's no benefit or requirement from having this library specified.
> Remove react-native-windows from `peerDependencies`

- .flowconfig
- src/package.json
- yarn.lock
This pull request fixes #340
It completely removes the *flow-bin* from dependencies mistakenly added along with Windows support.
---
The *flow-bin* is also required as a dev dependency, but it's there updated to the latest version: 0.163.0.
This update required some adjustments to be made to the *.flowconfig* so that it works as expected still.
> Remove redundant *flow-bin* dependency

- src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
- src/ios/RNCSlider.h
- src/ios/RNCSliderManager.m
- src/windows/SliderWindows/SliderView.cpp
- src/windows/SliderWindows/SliderView.h
**This pull request closes #292**
It introduces the improved control over the `value` property of the Slider and provides the user with the ability to control the thumb either by updating the `value` externally or by dragging/tapping the thumb.
(*This pull request also fixes #295 and closes #192*)
**NOTE:** This pull request affects all three platforms: iOS, Windows, Android
---
**How to use the new controlled `value` property?**
The `value` property should be considered **write-only**.
* It still does not need to be updated during dragging.
* Value written to that property will affect thumb's position immediately
* Updates to the `value` property **does not trigger** the `OnValueChange` event
What is programmatically written into `value` property should be tracked in the developer's …
> `value` property implemented as a controlled value

- README.md
- src/README.md
- src/package.json
- yarn.lock
This pull request updates the version of the package to 4.2.0.
It adds the controlled value feature.
The README has been updated to describe briefly on the controlled value.
> Release: Version 4.2.0

- .flowconfig
This pull request ignores all libraries in *node_modules* directory when it comes to flow checks.
Reasoning behind it:
* Some modules have their files malformed in purpose which leads to flow check fails for them, see facebook/flow#2364
* This fixes errors in dependabot PR #348 
* This speeds up the flow check of the sources in this library, reducing the CI minutes.
All comments against this change are welcomed.
> Ignore all node_modules

- example/SliderExample.js
- src/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- src/js/Slider.js
- src/js/__tests__/Slider.test.js
- src/js/__tests__/__snapshots__/Slider.test.js.snap
Summary:
---------
This issue fixes https://github.com/facebook/react-native/issues/30939 fixes https://github.com/facebook/react-native/issues/30840 ([Test Case 7.1][7.1], [Test Case 7.3][7.3], [Test Case 7.5][7.5]) .
The issue is caused by the missing prop `accessibilityState` in the Slider component.
The solution consists of passing the accessibilityState to the `RCTSliderNativeComponent` component as previously implemented in other components (for example, [Button][8]). 
Relevant discussions https://github.com/facebook/react-native/issues/30840#issuecomment-780981316 and https://github.com/facebook/react-native/pull/31001/files#r578827409.
[8]: https://github.com/facebook/react-native/pull/31224/files#diff-ab227579e3dfe69ff9b4952a09cf8ae78783e6fd9c2820f3c038e02c7406a6cdR171
The …
> Fix: Conflicting states for accessibility and non-accessibility users

- src/js/Slider.js
- src/js/__tests__/__snapshots__/Slider.test.js.snap
This pull request fixes #250
It adds the explicit implementation of utilizing the `onAccessibilityAction` property passed to the Slider exposed to JS side.
The implementation **does not** overrides the implementation of the event itself, but it takes that property directly from props passed to Slider as part of `ViewProps`.
The extracted property is explicity passed to Slider component implementation.
Tested on simulator using the Accessibility Inspector from Xcode tools.
> Fix: onAccessibilityAction causes crash

- src/typings/index.d.ts
This pull request fixes #321 
It introduces new type that is used as a type of optional `ref` value.
Root cause of the type error was that when Slider is used for non-web, the props given as rest (see the repro example) are treated as ref object, which does not meet the type specified for web implementation.
To keep the web implementation safe within this fix, new type keeps it along with the type deduced for props object ref.
> Fix: Type error when using Slider with props as ref

- src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java
This pull request fixes #377 
The fix is to avoid resetting the seekbar change listener when setting a value.
It turns out that when value is set for the first time (initial `value`) the seekbar is set, but it's resetting causes it to be removed and set to default Android's value of 0.
Removing the temporary blocking of setting the value fixes the issue.
---
This pull request has been also checked against the "controlled value" feature and defect of onChange not called.
Both these issues were not observed during testing the fix.
> Fix: Default/initial value ignored on Android

- src/ios/RNCSlider.h
- src/ios/RNCSlider.m
- src/ios/RNCSliderManager.m
This pull request fixes #390 
It allows to successfully use the `step` property which is considered during dragging and during programmatically control of the Slider.
The root cause of this issue was that the controlled `value` property modified the dragging logic changing the way the value is passed to `RNCSlider` instance according to sliding start and progress.
Due to that the `value` was given the unclipped value (uncalculated) during dragging which was assigned to the thumb only, but at the finish of the dragging the `value` of the whole component received the calculated one.
This resulted in observed smooth thumb transition, while `value` having the values respecting the `step` property.
The implementation of the fix moves the calculation of the discrete value which calculates the …
> Fix: ignored step value during dragging

- .github/workflows/ReactNativeSlider-CI.yml
This pull request fixes issues with cached Pods that were unable to use after downloading from cache.
The fix is to reinstall downloaded Pods so that the Pods project will get reintegrated between different build and environments.
> Fix: Pods-related error after using Pods from cache

- .github/workflows/ReactNativeSlider-CI.yml
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- example/package.json
- package/ios/RNCSlider.xcodeproj/project.pbxproj
- package/ios/RNCSliderComponentView.h
- package/ios/RNCSliderComponentView.mm
- package/package.json
- package/react-native-slider.podspec
- package/src/RNCSliderNativeComponent.js
- package/src/Slider.js
- package/src/index.js
Summary:
---------
- Setup codegen spec in flow
- Move `requireNativeComponent` to separate file
- Update podspec file
- Add codegenConfig in package.json
- Ensure backwards compatibility
- iOS Implementation
Test Plan:
----------
iOS: Install pods using `RCT_NEW_ARCH_ENABLED=1 pod install`
> Add fabric on iOS

- package/ios/RNCSliderComponentView.h
- package/ios/RNCSliderComponentView.mm
Summary:
---------
While playing with the example app I've discovered weird bug that caused images (`trackImage`, `thumbImage` etc.) to change their place and jump around (while rendering multiple sliders).
Here is a recording of this issue: 
https://user-images.githubusercontent.com/52801365/183864276-6e528e4c-93ca-4901-b5b5-2b7a98c89b8e.mp4
Test Plan:
----------
CI / Manual tests
> [Fabric] Fix hot reloading causing photo jumps

- package/android/build.gradle
This pull request fixes #415 
It avoids using dependencies that cannot be found for Android when building for older RN versions.
**How to test**
* Create new react native application with older version (v0.67, or v0.66)
* install latest (v4.3.0) Slider package,
* in node modules find the Slider and open build.gradle
./node_modules/@react-native-community/slider/android/build.gradle
* apply the changes done in this PR to the local project
* Build the app as usual
> Configure buildscript with gradle-plugin only for new arch

- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java
- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
According to [this discussion](https://github.com/reactwg/react-native-new-architecture/discussions/70#discussioncomment-3429973), ShadowNodes are not used in the new architecture so I moved it back to old arch. 
Regarding events: 
> `RCTModernEventEmitter` is a transitional replacement for `RCTEventEmitter` that works with Fabric and non-Fabric renderers. `RCTEventEmitter` works with Fabric as well, but there are negative perf implications and it should be avoided.
Source: [react-native source code](https://github.dev/facebook/react-native/blob/e0a71fc7b5cb8c264000147099be5b2575931193/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/RCTModernEventEmitter.java#L7)
Test Plan:
----------
CI
---
This pull request fixes #412
> [Fabric] Refactor events, remove unused code

- README.md
This pull request adds the link to the Project to the README.
It would be useful for some users/developers to be aware of the possibility to check the progress of an issue they are interested in.
The Project's board has been here for the beginning of my maintenance, but the goal is to keep all informed.
> Project's board mentioned in README

- package/package.json
Summary:
---------
Fixes https://github.com/callstack/react-native-slider/issues/430
Test Plan:
----------
Can't really test as it seems it needs to be packed first? I tried pointing to my fork, but it complains 😅
> Fix: move postinstall script to prepack

- package/typings/index.d.ts
Summary:
---------
Found myself wanting to use the `accessibilityUnits` and `accessibilityIncrements` props to enhance screen reader experience in the app I am working on. When trying to figure out what data-type should be passed to `accessibilityIncrements` I realised that the TypeScript documentation was just a copy of the `accessibilityUnits` documentation. The correct documentation for `accessibilityIncrements` was however written in the JavaScript implementation, so I copied it over to the TypeScript documentation.
Test Plan:
----------
Only documentation changes, no testing required
> Copy over correct documentation for accessibilityIncrements

- .github/workflows/ReactNativeSlider-CI.yml
This pull request adds launching the CI on pull request.
The `pull_request` was added to the list of events triggering the full CI.
**NOTE:** This PR was made from fork to test whether creating this PR will trigger the CI on the original upstream.
> Run the CI on pull request

- package/package-lock.json
- package/package.json
Summary:
---------
@types/react-test-renderer was added for a test but was added as a `dependency` rather than a `devDependency`. This results in it being a transitive prod dependency for any project using react-native-slider.
Test Plan:
----------
npm run lint and npm run test ran.
test still passes. lint complains no more than it did before the change was made against main.
> Fix @types being present as a prod dependency

- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java
Summary:
---------
Over on https://github.com/callstack/react-native-slider/issues/437, we see issues on Android...sometimes. Long story short, Reanimated intercepts event dispatching, and it calls the method removed in #422. (there's some more detail in [this](https://github.com/callstack/react-native-slider/issues/437#issuecomment-1282577509) comment)
We can see in the stacktrace that `dispatchModern()` isn't being called when dispatched via Reanimated:
The [react-native source](https://github.com/facebook/react-native/blob/f6cfcc3fc9e0b13d854f3c5295b67794507706c6/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java#L168-L172) describes the fix: don't override `dispatch()` and `dispatchModern()`, but simply override `getEventData()`. This PR does that, and seems to …
> Replace dispatchModern() calls with getEventData()

- README.md
- example/src/Examples.tsx
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java
- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/src/RNCSliderNativeComponent.ts
- package/src/RNCSliderNativeComponent.web.tsx
- package/src/Slider.tsx
- package/src/__tests__/__snapshots__/Slider.test.tsx.snap
Summary:
---------
Removing redundant "enabled" property as discussed in https://github.com/callstack/react-native-slider/pull/424#discussion_r966294006 and documented in https://github.com/callstack/react-native-slider/issues/426
Fixed some instructions in README as well:
- iOS: "`npm run ios` in `example/ios` folder" instead of "`npm run example-ios`" <-- the other command runs `pod-install` which installs pods with old arch
- Android: adding note that after changing settings to new architecture, first run fails for some reason and other ones are running fine 🤷 
Test Plan:
----------
Enabled "disabled" example for all platforms, so run the examples and test it out :)
iOS:
Android:
> fix: remove redundant "enabled" property

- .github/workflows/ReactNativeSlider-CI.yml
This pull request changes the way the events are triggered for the CI workflow.
It makes the CI to run for specific cases of PR, **or** for pushes made only to specific branches: `main` and `release/`.
The main reasoning behind this is to:
avoid multiple triggers of the same workflow
save some minutes for unnecessary runs.
> Refactor the workflows events triggers

- example/ios/Podfile.lock
- example/package-lock.json
- example/package.json
- example/src/App.tsx
- example/src/Props.tsx
- example/tsconfig.json
This pull request extends the Slider's Example app with new Tab: `Props`.
This new tab contains the examples of Slider each representing a single property, in the same order as in README.
**Reasoning**:
I do wanted to review all props regarding which works on what platform. I wanted to refresh them and the README at the same time and keep it updated forever as well.
So this new Tab contains the most raw examples of a single property each, without special attributes or styles or user's scenario. So I can launch the app and just check whether something has changed with a prop or make sure that after some time README stays up to date regarding the docs and library development.
**NOTE:** This tab is no fancy - it's purpuse is to act as a source of truth only. Sliders are presented with the …
> Include all properties in Example app - `Props` tab

- README.md
- example/package-lock.json
- example/src/Examples.tsx
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java
- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/babel.config.json
- package/ios/RNCSlider.h
- package/ios/RNCSliderComponentView.h
- package/ios/RNCSliderComponentView.mm
- package/ios/RNCSliderManager.m
- package/src/RNCSliderNativeComponent.ts
- package/src/Slider.tsx
- package/src/__tests__/Slider.test.tsx
- package/src/__tests__/__snapshots__/Slider.test.tsx.snap
- package/typings/index.d.ts
Summary:
---------
Feature to add slide limit. This will prevent sliding past the limit.
- Added new `upperLimit` and `lowerLimit` props to Slider.
- Implemented `upperLimit` and `lowerLimit` on iOS and Android for fabric and paper.
Test Plan:
----------
> feature: Add slide limit to iOS and Android

- README.md
Summary:
---------
Update the readme documentation regarding `web`.
Test Plan:
----------
Examine the README.md file.
> docs(web): update the readme documentation about web

- package/src/RNCSliderNativeComponent.web.tsx
Summary:
---------
This PR fixes a bug that occurs on web when the `minimumValue` or `maximumValue` are updated. Previously, the UI failed to update the animations when these props were mutated, but this fixes that.
Test Plan:
----------
You can test this by mutating the aforementioned values and confirming that the animations get appropriately updated.
> fix(web): mutating minimumValue and/or maxiumumValue failed to update UI

- example-web/src/Examples.tsx
- package/src/RNCSliderNativeComponent.web.tsx
Summary:
---------
Fixes #471.
As there is no native way to listen for changes to `getBoundingClientRect()`, the web implementation of Slider must cache and try to correctly invalidate the measurements. The code already does this on layout and when the viewport is resized, but not when the slider's bounding rect changes due to scrolling. This PR registers a capturing `scroll` event handler on `document` and invalidates the cache when an ancestor of the slider scrolls. This is probably not airtight (see this [StackOverflow discussion](https://stackoverflow.com/questions/40251082/an-event-or-observer-for-changes-to-getboundingclientrect)) but is AFAICT correct.
For performance, it may be worth experimenting with unregistering the `scroll` (and `resize`) listener once the cache has been …
> fix(web): invalidate position on ancestor scroll

- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
This pull request fixes #395 
It prevents from sending the `onValueChanged` event if it **does not** come from user's interaction.
Instead - it sends the `onSlidingComplete` event when the programmatic change happens so it's clear when value is updated without actually changing it via sliding.
This pull request has been tested against comparison between iOS and Android platforms. Please see the attached demo recorded during final testing:
https://user-images.githubusercontent.com/70535775/212943723-fe9e9005-4128-4e45-a72e-7dca8a1b5107.mov
> Avoid sending 'onValueChanged' on programmatic slide event

- package/typings/index.d.ts
Summary:
---------
Updating to react native 0.71, TypeScript errors on this library. The utility type `Constructor` is private in latest typings. Using this export degrades to `any` type.
`JSX element class does not support attributes because it does not have a 'props' property.`
Test Plan:
----------
`npx tsc` runs clean after making this change on a RN 0.71 app.
> fix(types): utility type removed from RN 0.71

- package/windows/SliderWindows/SliderWindows.vcxproj
Summary:
---------
In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72
Test Plan:
----------
tested on react native windows gallery
> fix: windows bump WindowsTargetPlatformMinVersion

- .github/workflows/ReactNativeSlider-CI.yml
This pull request fixes an issue in CI workflow of missing check for existing deps before installing new.
This saves a bit of time for init steps in CI.
> Check for existing cached dependencies before installing new

- package/src/Slider.tsx
- package/src/__tests__/__snapshots__/Slider.test.tsx.snap
This pull request fixes #345
It prevents the `value` prop to be sent to Slider when it is not a valid number.
The fix was tested using the repro scenario from the original issue, recording below:
https://github.com/callstack/react-native-slider/assets/70535775/fe817cbf-0f65-4646-884b-634c7d0105a4
> Fix: Avoid passing `value` prop if it's not a valid number

- README.md
This pull request closes #447 and #452 
It updates the compatibility table in README so that users/developers will be aware that using Slider after introducing new architecture should be done with react native version of at least 0.64.
> Update the compatibility table in README

- package/ios/RNCSliderComponentView.mm
- package/ios/RNCSliderManager.m
This pull request fixes #469 for iOS platform, where tapping (not dragging) would allow to set the `value` outside of the `lowerLimit` and `upperLimit`.
https://github.com/callstack/react-native-slider/assets/70535775/ea358b9e-c8d8-4a79-a197-096f4adcddd6
> Prevent from tapping beyond or outside of limits

- example/ios/Podfile.lock
- example/package-lock.json
- package/package-lock.json
- package/package.json
This pull request updates Slider package to v4.4.3
> Release: version 4.4.3

- package/react-native-slider.podspec
In RN 0.70, the core team introduced the `install_modules_dependencies` function to properly configure the iOS dependencies in the podspec.
This allow the Core team to add/remove flags and restructure the internal Cocoapods' structure of React Native and limiting the chances to break 3rd parties dependencies, as those changes will be captured by the function.
By not using this function, all the 3rd party libraries would have to chase and manually reimplement the same changes that the RN Core team applies to the Cocoapods structure. 
```
npx react-native@next init NewApp --version next --skip-install
cd NewApp
yarn add @react-native-community/slider   
yarn install
cd ios
bundle install
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
open NewApp.xcworkspace
```
Build and observe the …
> [iOS] Use install_module_dependencies in podspec file

- package/android/build.gradle
Summary:
---------
This is the minimum required change for this module to work on react-native 0.73 which includes android gradle plugin 8
This module does not just require namespace it also requires the buildConfig feature turned on, as discovered in actual use in a work app as I tested AGP8+ to fix up modules I maintain and modules I depend on
* Supercedes #519
It is similar to changes I needed to do as react-native-firebase maintainer --> https://github.com/invertase/react-native-firebase/commit/b52d0ce6723c077190618641ce0f33ced9fd4090
With apologies, you have to alter an app that integrates this module to use android gradle plugin 8, it's difficult to do that in repos I'm proposing these changes in because bumping to android gradle plugin 8 requries a large amount of transitive …
> fix(android): android gradle plugin 8 compatibility

- package/react-native-slider.podspec
Summary:
---------
This PR adds visionOS support.
https://github.com/callstack/react-native-slider/assets/52801365/2d9460f4-2b53-47d4-9e1a-74e55b3ebc17
Test Plan:
----------
1. Init the `visionos` app with: `npx @callstack/react-native-visionos init MyApp`
2. Add slider
3. Test if it works
> feat: add visionos support

- package/src/RNCSliderNativeComponent.web.tsx
- package/src/Slider.tsx
**Changes:**
1. **Web-Specific onValueChange**: Adjusted `onValueChange` in `RNCSliderNativeComponent.web.tsx` to trigger only during user interactions, addressing platform-specific inconsistencies (issue #562).
2. **Deprecated React Methods**: Updated `Slider.tsx` and `RNCSliderNativeComponent.web.tsx`, replacing deprecated `StyleSheet.compose` with array syntax.
These updates fixes an inconsistency in the web platform and improves compatibility with newer React versions.
Related Issue: #562
> Web-Specific Fixes for onValueChange and Deprecated React Methods

- README.md
- example-web/src/Examples.tsx
- package/src/RNCSliderNativeComponent.web.tsx
- package/src/Slider.tsx
Continues on abandoned PR: https://github.com/callstack/react-native-slider/pull/520
Summary:
---------
Add upperLimit support and lowerLimit support to web.
Test Plan:
----------
Also added an example to the web-example project.
https://github.com/callstack/react-native-slider/assets/38087818/32c09f40-cbc4-4dec-ba51-0cda036ef442
> feat: add slider limits to web

- .github/workflows/ReactNativeSlider-CI.yml
Summary:
---------
- Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, actions/cache@v3.0.7.
- For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> chore: update actions to latest versions

- .github/workflows/ReactNativeSlider-CI.yml
- example/ios/Podfile.lock
- package/android/build.gradle
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java
- package/android/src/main/jni/CMakeLists.txt
- package/android/src/main/jni/RNCSlider.h
- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderComponentDescriptor.h
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderMeasurementsManager.cpp
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderMeasurementsManager.h
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderShadowNode.cpp
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderShadowNode.h
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderState.cpp
- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderState.h
- package/ios/RNCSliderComponentView.mm
- package/package.json
- package/react-native-slider.podspec
- package/react-native.config.js
- package/src/RNCSliderNativeComponent.ts
Summary:
---------
This PR adds C++ shadow nodes to implement proper measuring for Android on Fabric/Bridgeless.
This code was based on Core implementation: https://github.com/facebook/react-native/blob/2af1da42ff517232f1309efed7565fe9ddbbac77/packages/react-native/ReactCommon/react/renderer/components/switch/androidswitch/react/renderer/components/androidswitch/AndroidSwitchShadowNode.cpp
Test Plan:
----------
Check if on new architecture Slider is properly rendered without any styles
> fix: new arch measurements on Android

- package/common/cpp/react/renderer/components/RNCSlider/RNCSliderMeasurementsManager.h
Summary:
---------
When compiling for the new architecture the build fails on android because of a missing header guard in `RNCSliderMeasurementsManager.h`
Test Plan:
----------
Issue can be reproduced in the example app in the repo.  Adding the guard compiles successfully.
> Fix missing header guard

- .github/workflows/ReactNativeSlider-CI.yml
- .gitignore
- example/android/gradle.properties
- package/android/src/main/jni/CMakeLists.txt
This pull request fixes #594 
It basically removes the unused and non-existing libraries from CMake config so that we don't require them when we don't really have them (nor build them on our own).
I briefly checked for the rest of the libs that are included there to see whether there's any other that can be removed, but it seems all other are indeed used and available during the build.
This pull request also introduces the job for building the new arch for Android, so that we can always check whether we are good there.
> Fix: Linking during Android build for new arch

- package/src/RNCSliderNativeComponent.web.tsx
Summary:
---------
Referencing this issue: #617
React native web implementation had no default value set for initial value therefore resulting in such issues.
According to mobile implementation and documentation set the default value for initialValue prop to be 0.
Test Plan:
----------
Verified on controlled examples from example-web by setting initial useState value to undefined
> fix: set default initial value on web

- README.md
Summary:
---------
Regarding issue #596 
Recent upgrade of supported RN version removes support for versions older than RN 69, meaning that last compatible version of library is 4.5.0
Test Plan:
----------
No tests required
> chore: add info about current compatibility

- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
Summary:
---------
closes #569 
In Seekbar overriden method onStopTrackingTouch was emitting two events - which might caused unwanted emission of onValueChange, removing this seems to not break any logic or behaviour but fixes the problem described.
Test Plan:
----------
I have ran the example app on old arch and all examples seems to work correctly
> fix: remove additional onchange event in onStopTrackingTouch

- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/ios/RNCSlider.m
- package/ios/RNCSliderComponentView.mm
- package/ios/RNCSliderManager.m
- package/src/Slider.tsx
Summary:
---------
fixes: #571 
Apply additional check and move the progress calculation to Slider class
Test Plan:
----------
Have ran the application examples on new/old arch witch success - the crash is not happening anymore.
> fix: check for invalid configuration in limit settings

- example/src/Examples.tsx
- package/src/Slider.tsx
- package/src/__tests__/__snapshots__/Slider.test.tsx.snap
- package/src/utils/constants.ts
This pull request fixes #606 
It applies the fix found during the review of #581 
The fix separates the meaning of `step` from the resolution of step(s) when calculating the layout of the `StepMarker` scenario render.
> Fix the step resolution calculation for StepMarker and steps when default settings

- package/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java
- package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java
- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
Summary:
---------
fixes: #634 
Resolves case 1 from the issue - when using floating numbers like in example for step size, min and max value it could result in unexpected number of steps
Test Plan:
----------
Tested on android the case from example and some other floats
> fix: floating number problem on android

- package/react-native.config.js
Summary:
---------
When using the library in monorepo solutions or other non-standard types of projects the Slider will end up with a height of 0 and not work. (See #652)
Problem/fix:
-----------
When resolving the version inside `react-native-config` which is used by the autolinking gradle tasks, the wrong use of require was used.
This fix changes from using `require.main.require` -> `require`.
The difference is that require.main.require resolves from the entry point (main script), while require resolves from the location of the current file.
Fixes (partially) #652
Test Plan:
----------
See #652 for reproduction and tests. We've tested in in our BareExpo project, in a regular project (where it also previously did work) and in a project using react-native-test-app …
> Fixed wrong usage of require when resolving supportsCodegenConfig in react-native.config.js

- example/package.json
- package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
- package/src/RNCSliderNativeComponent.ts
- package/src/Slider.tsx
Summary:
---------
fixes #652 
Resolved incompatible interface generation for the codegen source.
Test Plan:
----------
> fix: new arch android interface

- example/ios/Podfile.lock
- example/package-lock.json
- package/package-lock.json
- package/package.json
This pull request releases Slider to version 4.5.4
> Release: version 4.5.4

- package/android/src/main/jni/CMakeLists.txt
Summary:
---------
the recently released 4.5.4 won't build when installed into a RN 0.76 project, due to breaking changes described in https://github.com/react-native-community/discussions-and-proposals/discussions/816
This PR fixes the build in a backward-compatible way, as recommended in the link above
the build failure:
```
C/C++: /Users/vojta/_dev/expo/node_modules/@react-native-community/slider/android/src/main/jni/../../../build/generated/source/codegen/jni/react/renderer/components/RNCSlider/EventEmitters.h:12:10: fatal error: 'react/renderer/components/view/ViewEventEmitter.h' file not found
C/C++: #include <react/renderer/components/view/ViewEventEmitter.h>
C/C++:          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C/C++: 1 error generated.
C/C++:
```
and a bunch more of …
> fix: unblock build for 0.76

- package/package.json
Summary:
---------
When installing this package with RN 0.77 there's a warning related to the missing field in `codegenConfig`:
```
[Codegen] [DEPRECATED] @react-native-community/slider should add the 'ios.componentProvider' property in their codegenConfig
```
This PR fixes it 👍
Test Plan:
----------
1. Create an app with RN 0.77
2. Apply diff
3. Install Cocoapods
> feat: add component provider field for codegen

- package/ios/RNCSliderComponentView.mm
- package/ios/RNCSliderManager.m
Summary:
---------
When `tapToSeek` option is enabled it works as expected on LTR, however after changing the application to RTL it seeks to the inverted tap location.
Test Plan:
----------
Before:
https://github.com/user-attachments/assets/61192081-7f05-4250-a052-2832dbb460da
After:
https://github.com/user-attachments/assets/832a03e6-e790-4c15-a5f4-c6a47946f8ec
> fix: ios inverted tap to seek in rtl

- README.md
This pull request
* removes the migration part from README
I didn't find it any longer required, as this package is here for some time (years) now and settled down pretty well already.
* adds the official channel on Discord, where community can ask questions, issues, ping devs, etc.
> Remove migration instruction and link the Slider channel on Discord

- package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
Summary:
---------
Fix android auto increment issued on new arch (See [#683](https://github.com/callstack/react-native-slider/issues/683)). 
Added same check `if(fromUser)` that is present in the old architecture.
https://github.com/callstack/react-native-slider/blob/e9084f6adcd32e39cda62322a8209f6ac098a33f/package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java#L37-L42
Test Plan:
----------
Used [#683](https://github.com/callstack/react-native-slider/issues/683) as a template for bare react native project, to reproduce the issue and  check if it is still present. 
| Before  | After  |
|---------|--------|
| ![Before](https://github.com/user-attachments/assets/b5cdf984-0f8e-4b2e-9791-505452e5d0d8) | …
> fix: android auto increment on new arch

- package/src/Slider.tsx
- package/src/__tests__/__snapshots__/Slider.test.tsx.snap
Summary:
---------
When applying styles to the `Slider`, some styles are overwritten by the `defaultStyles`. This can lead to behaviour which the user does not expect. Closes #680 
Test Plan:
----------
1. Run the example app with no changes
2. Observe the slider components
3. Add a `style` prop with `height: 40` to any of the examples
4. Observe the height property is applied correctly to the slider
> Fix styles order

- example-web/package-lock.json
- example-web/package.json
- example-web/src/Examples.tsx
- example-web/src/Props.tsx
- package/src/RNCSliderNativeComponent.web.tsx
- package/src/Slider.tsx
- package/tsconfig.json
Summary:
---------
Fixes #701
Fixes #695
`defaultProps` and `findDOMNode` were removed in React 19.
For `findDOMNode`: it wasn't actually needed, as the ref is already pointed at the element. I added `dom` to the TS libs to support the type, but we can use a ts-ignore if you don't want that.
For `defaultProps`: I moved the values to default parameters in the function component and cleaned up the logic some
Test Plan:
----------
`example-web` is updated to react 19 and fully working now.
I haven't gotten a chance to test this on native yet
> React 19 fixes

- example/ios/Podfile.lock
- example/package-lock.json
- package/package-lock.json
- package/package.json
This pull request releases Slider with version 4.5.7.
> Release: v4.5.7

- package/android/src/main/jni/CMakeLists.txt
Summary:
---------
Trying to use `react-native-slider` with react-native 0.81.0-rc.5 will cause an insta crash in the app due to an issue when parsing `RNCSliderProps` on Android
These changes are related to the Props 2.0 project and require us to set the necessary flags and definitions in Cmake, by using `target_compile_reactnative_options` this can be done automatically instead of setting them manually.
Test Plan:
----------
1. `npx @react-native-community/cli@latest init RC5 --skip-install --version next`
2. `yarn add @react-native-community/slider`
3. patch `package/android/src/main/jni/CMakeLists.txt`
> fix: support for react native 0.81 on Android
